// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_tDzMauMklvFzuaJ8XcpVBgHU0yhWkxQ',
    appId: '1:327090325325:web:44115e1bd8d8c044981904',
    messagingSenderId: '327090325325',
    projectId: 'vendeco-99246',
    authDomain: 'vendeco-99246.firebaseapp.com',
    databaseURL: 'https://vendeco-99246-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vendeco-99246.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoAGz3XE9UrLD3gcwLVsB7rt-kLbhWQKk',
    appId: '1:327090325325:android:26678313492026ca981904',
    messagingSenderId: '327090325325',
    projectId: 'vendeco-99246',
    databaseURL: 'https://vendeco-99246-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vendeco-99246.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwIQXwmfCzsWN_fI5FVUibUNhvmeBmfP0',
    appId: '1:327090325325:ios:9732bcbaaf94c157981904',
    messagingSenderId: '327090325325',
    projectId: 'vendeco-99246',
    databaseURL: 'https://vendeco-99246-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vendeco-99246.appspot.com',
    iosClientId: '327090325325-4p5fgt6rlh0bjbfo6hffgptmt2m8gpo7.apps.googleusercontent.com',
    iosBundleId: 'com.vendeco.vendeco',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwIQXwmfCzsWN_fI5FVUibUNhvmeBmfP0',
    appId: '1:327090325325:ios:9732bcbaaf94c157981904',
    messagingSenderId: '327090325325',
    projectId: 'vendeco-99246',
    databaseURL: 'https://vendeco-99246-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vendeco-99246.appspot.com',
    iosClientId: '327090325325-4p5fgt6rlh0bjbfo6hffgptmt2m8gpo7.apps.googleusercontent.com',
    iosBundleId: 'com.vendeco.vendeco',
  );
}
